apiVersion: v1
kind: Service
metadata:
  name: solicitacao-service
  labels:
    app: solicitacao
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: solicitacao
